#!/bin/bash

############################################################################
#
# 本定制工具完全免费，DsiXDA版权所有，由MAL神族-沉默之星完成汉化翻译。
# 
# 理论上支持所有民间刷机包的定制，完美支持HTC的所有民间和官方刷机包！
#
# 欢迎光临全球最大中兴社区：神族论坛（http://bbs.malshenzu.com/）
#
############################################################################

version=0.224


if [ ! -e menu ]
then
  echo
  echo "确保你是从这个文件所在文件夹运行，"
  echo "否则厨房将会在运行脚本的时候出现问题。"
  echo "当你使用 'cd' 到正确的文件夹, 用 ./menu 命令"
  echo "运行厨房工具, 不要尝试其它的命令或方法!"
  exit 0
fi

dir_list=( original_update scripts tools )
error_found=0

for check_dir in ${dir_list[@]}
do
  if [ ! -e $check_dir ]
  then
    echo "错误: '$check_dir' 文件夹找不到"
    error_found=1
  fi
done

if [ $error_found == 1 ]
then
  echo
  echo "确保你已正确安装了厨房文件夹。"
  exit 0
fi


chmod 755 scripts/*
scripts/check_install_dir

if [ "$?" == "1" ]
then
  exit 0
fi

scripts/init_kitchen
scripts/check_binaries

if [ "$?" == "1" ]
then
  exit 0
fi


while :
do

  clear

  echo 
  echo "============================================================"
  echo " SYJ-APK-TOOL厨房插件 $version by MAL神族-沉默之星（汉化）"
  echo "============================================================"
  echo 
  echo "> 主菜单"
  echo
  echo "  1 - 导入 ROM 文件到工作文件夹"
  echo "  2 - 添加 root 最高权限"
  echo "  3 - 添加 BusyBox 指令集"
  echo "  4 - 关闭开机画面音乐"
  echo "  5 - 对所有 Apk 文件进行 Zipalign 操作，优化内存占用"
  echo "  6 - 更改 ROM 的 Wipe 操作状态"
  echo "  7 - 更改 ROM 显示名称"
  echo "  8 - 显示工作文件夹信息"
  echo 
  echo "  0 - 高级操作菜单"
  echo " 00 - 遗留选项 (旧的和很少使用的)"
  echo " 99 - 从工作文件夹建立 ROM 刷机包"
  echo
  echo "  u - 更新/关于厨房"
  echo "  x - 退出"
  echo
  echo 
  echo -n "请输入选择项: "
  read opt

  if [ "$opt" != "x" ] && [ "$opt" != "u" ] && [ "$opt" != "1" ]
  then
    scripts/check_multiple_working
  fi
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) clear; scripts/check_rom; continue;;
      2) scripts/do_root; continue;;
      3) scripts/add_busybox show_help;;
      4) scripts/disable_sounds;;
      5) scripts/do_zipalign;;
      6) scripts/change_wipe;;
      7) scripts/change_rom_name;;
      8) scripts/show_rom_info;;
      0) scripts/menu_advanced $version; continue;;
      00) scripts/menu_legacy $version; continue;;
      99) scripts/build_rom;;
      u) scripts/about $version; continue;;
      x) scripts/init_kitchen; clear; echo; echo "再见，欢迎光临神族论坛（http://bbs.malshenzu.com/），神族与你共进步！"; echo; exit 1;;
      *) echo "错误选项"; continue;;
    esac
  fi

  scripts/press_enter

done

